[package]
name = "make_data"
version = "0.1.7"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
rand = "0.9.1"
csv = "1.3"
fake = "4.3.0"
colored = "3.0.0"
toml = "0.9.0"
#serde = "1.0.219"
serde = {version = "1.0.218", features = ["derive"]}

